### ISSUE TITLE
Coin endpoints

### ISSUE THREAD

**Issue by aljaz-kokol** [RUPS-FERI/backend#9]
Create endpoints for the Coin entity.

#### Technical description
- Prepare 2 endpoints for fetching list of coins and getting a single coin by id
- Getting a list of coins
  -  returned properties ```name, code, files, slug```
  - query parameters must contain `page` and `size` (pagination)
  - optional query parameter `search` for filtering coins by fields `name` and `code`
- Getting a single coin by id should return all of the coins properties
  - when returning `prices` only fetch the last 20

**Comment by TravokG** [comment]
Coin endpoints
